### PR TITLE
Locale-specific pluralization rules

### PR DESCRIPTION
**Pull request by mamantoha**

### CODE REVIEW

**Comment by TechMagister** [comment]
Thanks for your work !
I see you made  some changes recently, is it still a work in progress ?

**Comment by mamantoha** [comment]
Yeah, I did some corrections while testing with my libraries. But now it is ready to review.

**Comment by straight-shoota** [comment]
I don't think the user should need to define pluralization rules. There are only a handful of different rulesets and they can easily be included in this shard, could even be hard coded. There is an overview on [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#List_of_Plural_Rules) which could serve as a basis. Default mappings for major languages should also be provided.

**Comment by TechMagister** [comment]
The existing rulesets can be hardcoded, but why not keeping the flexibility for the user to define custom rules ?

**Comment by straight-shoota** [comment]
As long as there are default rules which require no special configuration for all typical use cases, a customization option on top doesn't hurt. But I don't see why you would need it. I'd only add that complexity if there is a use case for it (and it can be added later should there be demand). All relevant use cases I can think of should be satisfied by implementing the standard ruleset.

**Comment by mamantoha** [comment]
Hi. So, what we will do with this? Any chance this will be merged, or I should close it?

**Pull request closed without merging**
